# -*- coding: utf-8 -*-

DEFAULT_PIECE_SIZE = 4096 * 8

DEFAULT_MAX_CONNECTION = 1

CACHED_COUNTS = DEFAULT_MAX_CONNECTION * 4
if CACHED_COUNTS < DEFAULT_MAX_CONNECTION * 2:
	CACHED_COUNTS = DEFAULT_MAX_CONNECTION * 2